<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryCurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
            ["country" => "Afghanistan", "currency_name" => "Afghani", "currency_code" => "AFN"],
            ["country" => "Albania", "currency_name" => "Lek", "currency_code" => "ALL"],
            ["country" => "Algeria", "currency_name" => "Dinar", "currency_code" => "DZD"],
            ["country" => "Andorra", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Angola", "currency_name" => "Kwanza", "currency_code" => "AOA"],
            ["country" => "Antigua and Barbuda", "currency_name" => "East Caribbean Dollar", "currency_code" => "XCD"],
            ["country" => "Argentina", "currency_name" => "Peso", "currency_code" => "ARS"],
            ["country" => "Armenia", "currency_name" => "Dram", "currency_code" => "AMD"],
            ["country" => "Australia", "currency_name" => "Dollar", "currency_code" => "AUD"],
            ["country" => "Austria", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Azerbaijan", "currency_name" => "Manat", "currency_code" => "AZN"],
            ["country" => "Bahamas", "currency_name" => "Dollar", "currency_code" => "BSD"],
            ["country" => "Bahrain", "currency_name" => "Dinar", "currency_code" => "BHD"],
            ["country" => "Bangladesh", "currency_name" => "Taka", "currency_code" => "BDT"],
            ["country" => "Barbados", "currency_name" => "Dollar", "currency_code" => "BBD"],
            ["country" => "Belarus", "currency_name" => "Ruble", "currency_code" => "BYN"],
            ["country" => "Belgium", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Belize", "currency_name" => "Dollar", "currency_code" => "BZD"],
            ["country" => "Benin", "currency_name" => "West African CFA franc", "currency_code" => "XOF"],
            ["country" => "Bhutan", "currency_name" => "Ngultrum", "currency_code" => "BTN"],
            ["country" => "Bolivia", "currency_name" => "Boliviano", "currency_code" => "BOB"],
            ["country" => "Bosnia and Herzegovina", "currency_name" => "Convertible Mark", "currency_code" => "BAM"],
            ["country" => "Botswana", "currency_name" => "Pula", "currency_code" => "BWP"],
            ["country" => "Brazil", "currency_name" => "Real", "currency_code" => "BRL"],
            ["country" => "Brunei", "currency_name" => "Dollar", "currency_code" => "BND"],
            ["country" => "Bulgaria", "currency_name" => "Lev", "currency_code" => "BGN"],
            ["country" => "Burkina Faso", "currency_name" => "West African CFA franc", "currency_code" => "XOF"],
            ["country" => "Burundi", "currency_name" => "Franc", "currency_code" => "BIF"],
            ["country" => "Cambodia", "currency_name" => "Riel", "currency_code" => "KHR"],
            ["country" => "Cameroon", "currency_name" => "Central African CFA franc", "currency_code" => "XAF"],
            ["country" => "Canada", "currency_name" => "Dollar", "currency_code" => "CAD"],
            ["country" => "Cape Verde", "currency_name" => "Escudo", "currency_code" => "CVE"],
            ["country" => "Central African Republic", "currency_name" => "Central African CFA franc", "currency_code" => "XAF"],
            ["country" => "Chad", "currency_name" => "Central African CFA franc", "currency_code" => "XAF"],
            ["country" => "Chile", "currency_name" => "Peso", "currency_code" => "CLP"],
            ["country" => "China", "currency_name" => "Yuan Renminbi", "currency_code" => "CNY"],
            ["country" => "Colombia", "currency_name" => "Peso", "currency_code" => "COP"],
            ["country" => "Comoros", "currency_name" => "Franc", "currency_code" => "KMF"],
            ["country" => "Congo (Democratic Republic)", "currency_name" => "Congolese Franc", "currency_code" => "CDF"],
            ["country" => "Congo (Republic)", "currency_name" => "Central African CFA franc", "currency_code" => "XAF"],
            ["country" => "Costa Rica", "currency_name" => "Colón", "currency_code" => "CRC"],
            ["country" => "Croatia", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Cuba", "currency_name" => "Peso", "currency_code" => "CUP"],
            ["country" => "Cyprus", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Czech Republic", "currency_name" => "Koruna", "currency_code" => "CZK"],
            ["country" => "Denmark", "currency_name" => "Krone", "currency_code" => "DKK"],
            ["country" => "Djibouti", "currency_name" => "Franc", "currency_code" => "DJF"],
            ["country" => "Dominica", "currency_name" => "East Caribbean Dollar", "currency_code" => "XCD"],
            ["country" => "Dominican Republic", "currency_name" => "Peso", "currency_code" => "DOP"],
            ["country" => "Ecuador", "currency_name" => "US Dollar", "currency_code" => "USD"],
            ["country" => "Egypt", "currency_name" => "Pound", "currency_code" => "EGP"],
            ["country" => "El Salvador", "currency_name" => "US Dollar", "currency_code" => "USD"],
            ["country" => "Equatorial Guinea", "currency_name" => "Central African CFA franc", "currency_code" => "XAF"],
            ["country" => "Eritrea", "currency_name" => "Nakfa", "currency_code" => "ERN"],
            ["country" => "Estonia", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Eswatini", "currency_name" => "Lilangeni", "currency_code" => "SZL"],
            ["country" => "Ethiopia", "currency_name" => "Birr", "currency_code" => "ETB"],
            ["country" => "Fiji", "currency_name" => "Dollar", "currency_code" => "FJD"],
            ["country" => "Finland", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "France", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Gabon", "currency_name" => "Central African CFA franc", "currency_code" => "XAF"],
            ["country" => "Gambia", "currency_name" => "Dalasi", "currency_code" => "GMD"],
            ["country" => "Georgia", "currency_name" => "Lari", "currency_code" => "GEL"],
            ["country" => "Germany", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Ghana", "currency_name" => "Cedi", "currency_code" => "GHS"],
            ["country" => "Greece", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Grenada", "currency_name" => "East Caribbean Dollar", "currency_code" => "XCD"],
            ["country" => "Guatemala", "currency_name" => "Quetzal", "currency_code" => "GTQ"],
            ["country" => "Guinea", "currency_name" => "Franc", "currency_code" => "GNF"],
            ["country" => "Guinea-Bissau", "currency_name" => "West African CFA franc", "currency_code" => "XOF"],
            ["country" => "Guyana", "currency_name" => "Dollar", "currency_code" => "GYD"],
            ["country" => "Haiti", "currency_name" => "Gourde", "currency_code" => "HTG"],
            ["country" => "Honduras", "currency_name" => "Lempira", "currency_code" => "HNL"],
            ["country" => "Hungary", "currency_name" => "Forint", "currency_code" => "HUF"],
            ["country" => "Iceland", "currency_name" => "Krona", "currency_code" => "ISK"],
            ["country" => "India", "currency_name" => "Rupee", "currency_code" => "INR"],
            ["country" => "Indonesia", "currency_name" => "Rupiah", "currency_code" => "IDR"],
            ["country" => "Iran", "currency_name" => "Rial", "currency_code" => "IRR"],
            ["country" => "Iraq", "currency_name" => "Dinar", "currency_code" => "IQD"],
            ["country" => "Ireland", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Israel", "currency_name" => "New Shekel", "currency_code" => "ILS"],
            ["country" => "Italy", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Jamaica", "currency_name" => "Dollar", "currency_code" => "JMD"],
            ["country" => "Japan", "currency_name" => "Yen", "currency_code" => "JPY"],
            ["country" => "Jordan", "currency_name" => "Dinar", "currency_code" => "JOD"],
            ["country" => "Kazakhstan", "currency_name" => "Tenge", "currency_code" => "KZT"],
            ["country" => "Kenya", "currency_name" => "Shilling", "currency_code" => "KES"],
            ["country" => "Kiribati", "currency_name" => "Dollar", "currency_code" => "AUD"],
            ["country" => "Korea (North)", "currency_name" => "Won", "currency_code" => "KPW"],
            ["country" => "Korea (South)", "currency_name" => "Won", "currency_code" => "KRW"],
            ["country" => "Kuwait", "currency_name" => "Dinar", "currency_code" => "KWD"],
            ["country" => "Kyrgyzstan", "currency_name" => "Som", "currency_code" => "KGS"],
            ["country" => "Laos", "currency_name" => "Kip", "currency_code" => "LAK"],
            ["country" => "Latvia", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Lebanon", "currency_name" => "Pound", "currency_code" => "LBP"],
            ["country" => "Lesotho", "currency_name" => "Loti", "currency_code" => "LSL"],
            ["country" => "Liberia", "currency_name" => "Dollar", "currency_code" => "LRD"],
            ["country" => "Libya", "currency_name" => "Dinar", "currency_code" => "LYD"],
            ["country" => "Liechtenstein", "currency_name" => "Franc", "currency_code" => "CHF"],
            ["country" => "Lithuania", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Luxembourg", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Madagascar", "currency_name" => "Ariary", "currency_code" => "MGA"],
            ["country" => "Malawi", "currency_name" => "Kwacha", "currency_code" => "MWK"],
            ["country" => "Malaysia", "currency_name" => "Ringgit", "currency_code" => "MYR"],
            ["country" => "Maldives", "currency_name" => "Rufiyaa", "currency_code" => "MVR"],
            ["country" => "Mali", "currency_name" => "West African CFA franc", "currency_code" => "XOF"],
            ["country" => "Malta", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Marshall Islands", "currency_name" => "US Dollar", "currency_code" => "USD"],
            ["country" => "Mauritania", "currency_name" => "Ouguiya", "currency_code" => "MRU"],
            ["country" => "Mauritius", "currency_name" => "Rupee", "currency_code" => "MUR"],
            ["country" => "Mexico", "currency_name" => "Peso", "currency_code" => "MXN"],
            ["country" => "Micronesia", "currency_name" => "US Dollar", "currency_code" => "USD"],
            ["country" => "Moldova", "currency_name" => "Leu", "currency_code" => "MDL"],
            ["country" => "Monaco", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Mongolia", "currency_name" => "Tugrik", "currency_code" => "MNT"],
            ["country" => "Montenegro", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Morocco", "currency_name" => "Dirham", "currency_code" => "MAD"],
            ["country" => "Mozambique", "currency_name" => "Metical", "currency_code" => "MZN"],
            ["country" => "Myanmar", "currency_name" => "Kyat", "currency_code" => "MMK"],
            ["country" => "Namibia", "currency_name" => "Dollar", "currency_code" => "NAD"],
            ["country" => "Nauru", "currency_name" => "Dollar", "currency_code" => "AUD"],
            ["country" => "Nepal", "currency_name" => "Rupee", "currency_code" => "NPR"],
            ["country" => "Netherlands", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "New Zealand", "currency_name" => "Dollar", "currency_code" => "NZD"],
            ["country" => "Nicaragua", "currency_name" => "Córdoba", "currency_code" => "NIO"],
            ["country" => "Niger", "currency_name" => "West African CFA franc", "currency_code" => "XOF"],
            ["country" => "Nigeria", "currency_name" => "Naira", "currency_code" => "NGN"],
            ["country" => "North Macedonia", "currency_name" => "Denar", "currency_code" => "MKD"],
            ["country" => "Norway", "currency_name" => "Krone", "currency_code" => "NOK"],
            ["country" => "Oman", "currency_name" => "Rial", "currency_code" => "OMR"],
            ["country" => "Pakistan", "currency_name" => "Rupee", "currency_code" => "PKR"],
            ["country" => "Palau", "currency_name" => "US Dollar", "currency_code" => "USD"],
            ["country" => "Panama", "currency_name" => "Balboa", "currency_code" => "PAB"],
            ["country" => "Papua New Guinea", "currency_name" => "Kina", "currency_code" => "PGK"],
            ["country" => "Paraguay", "currency_name" => "Guarani", "currency_code" => "PYG"],
            ["country" => "Peru", "currency_name" => "Sol", "currency_code" => "PEN"],
            ["country" => "Philippines", "currency_name" => "Peso", "currency_code" => "PHP"],
            ["country" => "Poland", "currency_name" => "Zloty", "currency_code" => "PLN"],
            ["country" => "Portugal", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Qatar", "currency_name" => "Riyal", "currency_code" => "QAR"],
            ["country" => "Romania", "currency_name" => "Leu", "currency_code" => "RON"],
            ["country" => "Russia", "currency_name" => "Ruble", "currency_code" => "RUB"],
            ["country" => "Rwanda", "currency_name" => "Franc", "currency_code" => "RWF"],
            ["country" => "Saint Kitts and Nevis", "currency_name" => "East Caribbean Dollar", "currency_code" => "XCD"],
            ["country" => "Saint Lucia", "currency_name" => "East Caribbean Dollar", "currency_code" => "XCD"],
            ["country" => "Saint Vincent and the Grenadines", "currency_name" => "East Caribbean Dollar", "currency_code" => "XCD"],
            ["country" => "Samoa", "currency_name" => "Tala", "currency_code" => "WST"],
            ["country" => "San Marino", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Sao Tome and Principe", "currency_name" => "Dobra", "currency_code" => "STN"],
            ["country" => "Saudi Arabia", "currency_name" => "Riyal", "currency_code" => "SAR"],
            ["country" => "Senegal", "currency_name" => "West African CFA franc", "currency_code" => "XOF"],
            ["country" => "Serbia", "currency_name" => "Dinar", "currency_code" => "RSD"],
            ["country" => "Seychelles", "currency_name" => "Rupee", "currency_code" => "SCR"],
            ["country" => "Sierra Leone", "currency_name" => "Leone", "currency_code" => "SLL"],
            ["country" => "Singapore", "currency_name" => "Dollar", "currency_code" => "SGD"],
            ["country" => "Slovakia", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Slovenia", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Solomon Islands", "currency_name" => "Dollar", "currency_code" => "SBD"],
            ["country" => "Somalia", "currency_name" => "Shilling", "currency_code" => "SOS"],
            ["country" => "South Africa", "currency_name" => "Rand", "currency_code" => "ZAR"],
            ["country" => "South Sudan", "currency_name" => "Pound", "currency_code" => "SSP"],
            ["country" => "Spain", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Sri Lanka", "currency_name" => "Rupee", "currency_code" => "LKR"],
            ["country" => "Sudan", "currency_name" => "Pound", "currency_code" => "SDG"],
            ["country" => "Suriname", "currency_name" => "Dollar", "currency_code" => "SRD"],
            ["country" => "Sweden", "currency_name" => "Krona", "currency_code" => "SEK"],
            ["country" => "Switzerland", "currency_name" => "Franc", "currency_code" => "CHF"],
            ["country" => "Syria", "currency_name" => "Pound", "currency_code" => "SYP"],
            ["country" => "Taiwan", "currency_name" => "Dollar", "currency_code" => "TWD"],
            ["country" => "Tajikistan", "currency_name" => "Somoni", "currency_code" => "TJS"],
            ["country" => "Tanzania", "currency_name" => "Shilling", "currency_code" => "TZS"],
            ["country" => "Thailand", "currency_name" => "Baht", "currency_code" => "THB"],
            ["country" => "Timor-Leste", "currency_name" => "US Dollar", "currency_code" => "USD"],
            ["country" => "Togo", "currency_name" => "West African CFA franc", "currency_code" => "XOF"],
            ["country" => "Tonga", "currency_name" => "Paʻanga", "currency_code" => "TOP"],
            ["country" => "Trinidad and Tobago", "currency_name" => "Dollar", "currency_code" => "TTD"],
            ["country" => "Tunisia", "currency_name" => "Dinar", "currency_code" => "TND"],
            ["country" => "Turkey", "currency_name" => "Lira", "currency_code" => "TRY"],
            ["country" => "Turkmenistan", "currency_name" => "Manat", "currency_code" => "TMT"],
            ["country" => "Tuvalu", "currency_name" => "Dollar", "currency_code" => "AUD"],
            ["country" => "Uganda", "currency_name" => "Shilling", "currency_code" => "UGX"],
            ["country" => "Ukraine", "currency_name" => "Hryvnia", "currency_code" => "UAH"],
            ["country" => "United Arab Emirates", "currency_name" => "Dirham", "currency_code" => "AED"],
            ["country" => "United Kingdom", "currency_name" => "Pound Sterling", "currency_code" => "GBP"],
            ["country" => "United States", "currency_name" => "Dollar", "currency_code" => "USD"],
            ["country" => "Uruguay", "currency_name" => "Peso", "currency_code" => "UYU"],
            ["country" => "Uzbekistan", "currency_name" => "Som", "currency_code" => "UZS"],
            ["country" => "Vanuatu", "currency_name" => "Vatu", "currency_code" => "VUV"],
            ["country" => "Vatican City", "currency_name" => "Euro", "currency_code" => "EUR"],
            ["country" => "Venezuela", "currency_name" => "Bolívar", "currency_code" => "VES"],
            ["country" => "Vietnam", "currency_name" => "Dong", "currency_code" => "VND"],
            ["country" => "Yemen", "currency_name" => "Rial", "currency_code" => "YER"],
            ["country" => "Zambia", "currency_name" => "Kwacha", "currency_code" => "ZMW"],
            ["country" => "Zimbabwe", "currency_name" => "Dollar", "currency_code" => "ZWL"],
        ]);
    }
}
